proto:
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./app/pb/users.proto
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./app/pb/tasks.proto
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./app/pb/notifications.proto