proto:
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./connection/pb/users.proto
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./connection/pb/tasks.proto
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./connection/pb/notifications.proto