version: '3'


services:

  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ./notifications
    restart: always
    image: izveigor/tasks-notifications
    container_name: tasks_notifications_production_server
    ports:
      - 8002:8002
      - 50053:50053
    networks:
      - gateway_network
      - mongo_network
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6
    container_name: tasks_notifications_production_mongo
    ports:
      - 27017:27017
    networks:
      - mongo_network


networks:
  gateway_network:
    external: true
  mongo_network: