export const USERS_URL = "http://localhost:8000/"
export const TASKS_URL = "http://localhost:8001/"
export const NOTIFICATION_URL = "http://localhost:8002/"
export const WS_NOTIFICATION_URL = "ws://localhost:8002/"
export const USERS_URL_WITHOUT_SLASH = "http://localhost:8000"