proto:
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./account/pb/users.proto
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./account/pb/tasks.proto
	python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. ./account/pb/notifications.proto