# Generated by Django 4.1.3 on 2022-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название команды:"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1500, verbose_name="Описание команды:"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images", verbose_name="Изображение команды:"
                    ),
                ),
            ],
        ),
    ]
