# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection/pb/users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63onnection/pb/users.proto\x12\x02pb\"%\n\x14\x41uthorizationRequest\x12\r\n\x05token\x18\x01 \x01(\t\"B\n\x11PermissionRequest\x12\x18\n\x10receiverUsername\x18\x02 \x01(\t\x12\x13\n\x0bsenderToken\x18\x01 \x01(\t\"F\n\x15\x41uthorizationResponse\x12\x1b\n\x13is_permission_exist\x18\x02 \x01(\x08\x12\x10\n\x08username\x18\x01 \x01(\t2\x9e\x01\n\x05Users\x12P\n\x19\x41uthorizationLikeTeammate\x12\x18.pb.AuthorizationRequest\x1a\x19.pb.AuthorizationResponse\x12\x43\n\x0f\x43heckPermission\x12\x15.pb.PermissionRequest\x1a\x19.pb.AuthorizationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection.pb.users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHORIZATIONREQUEST._serialized_start=33
  _AUTHORIZATIONREQUEST._serialized_end=70
  _PERMISSIONREQUEST._serialized_start=72
  _PERMISSIONREQUEST._serialized_end=138
  _AUTHORIZATIONRESPONSE._serialized_start=140
  _AUTHORIZATIONRESPONSE._serialized_end=210
  _USERS._serialized_start=213
  _USERS._serialized_end=371
# @@protoc_insertion_point(module_scope)
